stages:
  train:
    cmd: python -m src.train
    deps:
      - data/raw/diabetes.csv
      - config.ini
      - requirements.txt
      - src/config.py
      - src/features.py
      - src/datasets.py
      - src/feedback_dataset.py
      - src/data_preprocessing.py
      - src/pipelines.py
      - src/clinical_features_v1.py
      - src/train.py
      - src/logger.py
    params:
      - training.json:
          - models
    metrics:
      - reports/metrics.json:
          cache: false
    outs:
      - models:
          persist: true
      - reports/selected_parameters.json:
          cache: false
