-- Создано командой python -m scripts.generate_schema; не редактируйте вручную.


CREATE TABLE datasets (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	dataset_name VARCHAR(100) NOT NULL,
	dataset_version VARCHAR(64) NOT NULL,
	source_type VARCHAR(20) NOT NULL,
	source_path VARCHAR(1024) NOT NULL,
	source_sha256 VARCHAR(64) NOT NULL,
	row_count INTEGER NOT NULL,
	selection_filters JSONB NOT NULL,
	lineage_sha256 VARCHAR(64),
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CHECK (row_count > 0),
	CHECK (source_type IN ('raw','feedback')),
	CHECK (source_sha256 ~ '^[a-f0-9]{64}$'),
	UNIQUE (dataset_version)
)

;


CREATE TABLE users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	username VARCHAR(100) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	role VARCHAR(20) DEFAULT 'user' NOT NULL,
	is_active BOOLEAN DEFAULT true NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CHECK (role IN ('user','admin')),
	UNIQUE (username)
)

;


CREATE TABLE studies (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	patient_code VARCHAR(6) NOT NULL,
	study_date DATE NOT NULL,
	created_by BIGINT,
	pregnancies INTEGER NOT NULL,
	glucose NUMERIC NOT NULL,
	blood_pressure NUMERIC NOT NULL,
	skin_thickness NUMERIC NOT NULL,
	insulin NUMERIC NOT NULL,
	bmi NUMERIC NOT NULL,
	diabetes_pedigree_function NUMERIC NOT NULL,
	age INTEGER NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_study_patient_date UNIQUE (patient_code, study_date),
	CHECK (patient_code ~ '^[A-Z]{3}[0-9]{3}$'),
	CHECK (pregnancies BETWEEN 0 AND 20),
	CHECK (glucose BETWEEN 0 AND 600),
	CHECK (blood_pressure BETWEEN 0 AND 200),
	CHECK (skin_thickness BETWEEN 0 AND 110),
	CHECK (insulin BETWEEN 0 AND 1000),
	CHECK (bmi BETWEEN 0 AND 100),
	CHECK (diabetes_pedigree_function > 0 AND diabetes_pedigree_function <= 3),
	CHECK (age > 0 AND age <= 120),
	FOREIGN KEY(created_by) REFERENCES users (id) ON DELETE RESTRICT
)

;


CREATE TABLE training_runs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	release_id VARCHAR(64) NOT NULL,
	dataset_id BIGINT NOT NULL,
	configuration JSONB NOT NULL,
	provenance JSONB NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (release_id),
	FOREIGN KEY(dataset_id) REFERENCES datasets (id) ON DELETE RESTRICT
)

;


CREATE TABLE user_sessions (
	token_hash VARCHAR(64) NOT NULL,
	user_id BIGINT NOT NULL,
	password_fingerprint VARCHAR(64) NOT NULL,
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (token_hash),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
)

;

CREATE INDEX ix_user_sessions_expires_at ON user_sessions (expires_at);


CREATE TABLE dataset_rows (
	dataset_id BIGINT NOT NULL,
	row_number INTEGER NOT NULL,
	source_study_id BIGINT,
	features JSONB NOT NULL,
	outcome INTEGER NOT NULL,
	PRIMARY KEY (dataset_id, row_number),
	CHECK (row_number >= 0),
	CHECK (outcome IN (0,1)),
	FOREIGN KEY(dataset_id) REFERENCES datasets (id) ON DELETE RESTRICT,
	FOREIGN KEY(source_study_id) REFERENCES studies (id) ON DELETE RESTRICT
)

;


CREATE TABLE feedback (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	study_id BIGINT NOT NULL,
	created_by_user_id BIGINT,
	true_label INTEGER NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CHECK (true_label IN (0,1)),
	UNIQUE (study_id),
	FOREIGN KEY(study_id) REFERENCES studies (id) ON DELETE RESTRICT,
	FOREIGN KEY(created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT
)

;


CREATE TABLE feedback_history (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	study_id BIGINT NOT NULL,
	old_label INTEGER,
	new_label INTEGER NOT NULL,
	changed_by BIGINT,
	changed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CHECK (old_label IS NULL OR old_label IN (0,1)),
	CHECK (new_label IN (0,1)),
	FOREIGN KEY(study_id) REFERENCES studies (id) ON DELETE RESTRICT,
	FOREIGN KEY(changed_by) REFERENCES users (id) ON DELETE RESTRICT
)

;


CREATE TABLE model_versions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	model_name VARCHAR(100) NOT NULL,
	model_version VARCHAR(50) NOT NULL,
	family VARCHAR(100) NOT NULL,
	training_run_id BIGINT NOT NULL,
	artifact_path VARCHAR(1024) NOT NULL,
	artifact_sha256 VARCHAR(64) NOT NULL,
	artifact_format VARCHAR(30) NOT NULL,
	params_json JSONB NOT NULL,
	metrics JSONB NOT NULL,
	metadata_json JSONB NOT NULL,
	role VARCHAR(20) DEFAULT 'challenger' NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CHECK (role IN ('champion','challenger','archived')),
	CHECK (artifact_sha256 ~ '^[a-f0-9]{64}$'),
	UNIQUE (model_version),
	FOREIGN KEY(training_run_id) REFERENCES training_runs (id) ON DELETE RESTRICT
)

;

CREATE UNIQUE INDEX uq_model_versions_single_champion ON model_versions (role) WHERE role = 'champion';


CREATE TABLE study_edits (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	study_id BIGINT NOT NULL,
	changed_by BIGINT NOT NULL,
	features_before JSONB NOT NULL,
	features_after JSONB NOT NULL,
	predictions_before JSONB NOT NULL,
	changed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(study_id) REFERENCES studies (id) ON DELETE RESTRICT,
	FOREIGN KEY(changed_by) REFERENCES users (id) ON DELETE RESTRICT
)

;


CREATE TABLE model_role_history (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	model_version_id BIGINT NOT NULL,
	old_role VARCHAR(20),
	new_role VARCHAR(20) NOT NULL,
	changed_by BIGINT,
	changed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(model_version_id) REFERENCES model_versions (id) ON DELETE RESTRICT,
	FOREIGN KEY(changed_by) REFERENCES users (id) ON DELETE RESTRICT
)

;


CREATE TABLE predictions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	study_id BIGINT NOT NULL,
	model_version_id BIGINT NOT NULL,
	prediction INTEGER NOT NULL,
	probability FLOAT NOT NULL,
	role_at_prediction VARCHAR(20) NOT NULL,
	response_time_ms INTEGER,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_prediction_study_model UNIQUE (study_id, model_version_id),
	CHECK (prediction IN (0,1)),
	CHECK (probability BETWEEN 0 AND 1),
	CHECK (role_at_prediction IN ('champion','challenger')),
	CHECK (response_time_ms IS NULL OR response_time_ms >= 0),
	FOREIGN KEY(study_id) REFERENCES studies (id) ON DELETE RESTRICT,
	FOREIGN KEY(model_version_id) REFERENCES model_versions (id) ON DELETE RESTRICT
)

;
