"""Генерация SQL из ORM: один источник структуры и ограничений."""
from pathlib import Path
from sqlalchemy.schema import CreateTable, CreateIndex
from sqlalchemy.dialects import postgresql
from src.db.models import Base


def main():
    root = Path(__file__).resolve().parents[1]
    dialect = postgresql.dialect()
    statements = ["-- Generated by python -m scripts.generate_schema; do not edit manually."]
    for table in Base.metadata.sorted_tables:
        statements.append(str(CreateTable(table).compile(dialect=dialect)) + ";")
        for index in sorted(table.indexes, key=lambda item: item.name):
            statements.append(str(CreateIndex(index).compile(dialect=dialect)) + ";")
    content = "\n\n".join(statements)
    content = "\n".join(line.rstrip() for line in content.splitlines()) + "\n"
    (root / "db/01_schema.sql").write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
